// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfphqtthiifszwwmkvyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcGhxdHRoaWlmc3p3d21rdnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NzMzMTAsImV4cCI6MjA1MTI0OTMxMH0.PKto9d-QlQ6c6Ntsfap9-iMwqZArGKP7WIR1TgDhETo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);